(async () => {
  const checks = [];
  const mode = new URLSearchParams(location.search).get('test') || 'personal';
  const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
  const assert = (name, condition) => { if (!condition) throw new Error(name); checks.push('PASS ' + name); };
  try {
    for (let i=0; i<100 && $('postMealBtn').disabled; i++) await pause(50);
    if (mode === 'reader') {
      await refreshGroup();
      const post = meals.find(m => m.title === '<b>Photo test bowl</b>');
      assert('second browser sees shared photo and macros', post && post.image.startsWith('data:image/jpeg;base64,') && post.macros.protein === 0 && post.macros.carbs === null);
      assert('second browser sees first compliment', complimentState(post.id).count === 1 && !complimentState(post.id).active);
      await toggleCompliment(post.id);
      assert('second browser adds its own compliment', complimentState(post.id).count === 2 && complimentState(post.id).active);
      openRecipe(post.id);
      assert('shared photo in detail view', !$('modalImage').hidden && $('modalImage').src === post.image);
      assert('nutrition visible in detail view', $('modalMacros').textContent.includes('0') && $('modalMacros').textContent.includes('Self-reported'));
    } else {
      $('searchMeals').value = 'no matches';
      openProfile(' @PlatePal ');
      assert('profile ignores previous filters and matches normalized username', document.querySelectorAll('.meal-card').length === 6 && $('profileTitle').textContent === '@platepal');
      $('backToFeed').click();
      assert('back restores search', $('searchMeals').value === 'no matches');
      $('searchMeals').value = ''; renderMeals();
      document.querySelector('[data-profile="sophia.m"]').click();
      assert('clickable author isolates posts', document.querySelectorAll('.meal-card').length === 1);
      $('backToFeed').click();
      await toggleCompliment(1);
      assert('compliment is pressed and counted', document.querySelector('[data-compliment="1"]').getAttribute('aria-pressed') === 'true' && complimentState(1).count === 1);
      await toggleCompliment(1);
      assert('compliment can be undone', complimentState(1).count === 0);
      assert('sample feed loads', meals.filter(m => typeof m.id === 'number').length === 9);
      document.querySelector('[data-filter="budget"]').click();
      assert('budget category isolates affordable meals', document.querySelectorAll('.meal-card').length === 3);
      document.querySelector('[data-filter="protein"]').click();
      assert('protein category loads', document.querySelectorAll('.meal-card').length === 3);
      document.querySelector('[data-filter="quick"]').click();
      assert('quick category includes overlapping meals', document.querySelectorAll('.meal-card').length === 5);
      document.querySelector('[data-filter="all"]').click();
      document.querySelector('[data-scan="4"]').click();
      const count = groceries.length;
      document.querySelector('[data-scan="4"]').click();
      assert('ingredient scan deduplicates groceries', count === 6 && groceries.length === count);
      assert('grocery list has no individual delete buttons', !document.querySelector('#groceryList button'));
      const check = document.querySelector('[data-grocery="0"]'); check.click(); $('clearGroceries').click();
      assert('clear checked removes and persists only checked items', groceries.length === count - 1 && JSON.parse(localStorage.getItem('platePalGroceries')).length === count - 1);
      await Promise.all(meals.filter(m => m.id >= 4 && m.id <= 9).map(m => { const image = new Image(); image.src = m.image; return image.decode(); }));
      assert('all six stock photos load', meals.filter(m => m.id >= 4 && m.id <= 9).every(m => m.image.startsWith('images/')));
      openRecipe(4);
      assert('recipe source is linked', $('modalSource').querySelector('a').href.includes('bbcgoodfood.com'));
      closeModal($('recipeModal'));
      $('featuredRecipe').click();
      assert('featured recipe opens', currentMeal.id === 4 && !$('recipeModal').classList.contains('hidden'));
      closeModal($('recipeModal'));
      $('featuredSave').click();
      assert('featured meal saves', saved.includes(4));
      toggleSave(4);
      $('featuredShop').click();
      assert('featured shopping opens with ingredients', !$('shopModal').classList.contains('hidden') && groceries.length === 6);
      document.querySelector('[data-store="Target"]').click();
      $('previewBasket').click();
      assert('store basket preview is simulated', $('basketConfirmation').textContent.includes('Target') && $('basketConfirmation').textContent.includes('not placed an order'));
      document.querySelector('[data-basket-remove]').click();
      assert('basket removal updates saved list', groceries.length === 5 && JSON.parse(localStorage.getItem('platePalGroceries')).length === 5 && $('basketConfirmation').classList.contains('hidden'));
      closeModal($('shopModal'));
      document.querySelector('[data-grocery]').click();
      $('shopGroceriesBtn').click();
      assert('checked items excluded from basket', document.querySelectorAll('[data-basket-remove]').length === 4);
      while (document.querySelector('[data-basket-remove]')) document.querySelector('[data-basket-remove]').click();
      assert('empty basket cannot continue', $('previewBasket').disabled);
      $('shopModal').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
      assert('shopping dialog closes with Escape', $('shopModal').classList.contains('hidden'));
      assert('no price interest or coming soon copy', !document.body.textContent.includes('$4.99') && !document.body.textContent.toLowerCase().includes('coming soon'));
      for(let i=0;i<40 && !$('featuredVideo').readyState;i++) await pause(50);
      assert('featured video loads', $('featuredVideo').readyState > 0 && $('featuredVideo').duration > 10);

      $('interestName').value='Test Person'; $('interestEmail').value='tester@example.com'; $('interestConsent').checked=true;
      await $('interestForm').onsubmit({preventDefault(){}});
      assert('signup reports correct availability', $('interestStatus').textContent.includes(mode === 'personal' ? 'not been sent' : 'on the interest list'));
      const canvas = document.createElement('canvas'); canvas.width=1400; canvas.height=800;
      const ctx=canvas.getContext('2d'); ctx.fillStyle='#5c8b44'; ctx.fillRect(0,0,1400,800);
      const blob=await new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
      const file=new File([blob], 'meal.png', {type:'image/png'});
      const transfer=new DataTransfer(); transfer.items.add(file); $('mealPhoto').files=transfer.files;
      await $('mealPhoto').onchange();
      assert('photo upload preview', photoData.startsWith('data:image/jpeg;base64,') && !$('photoPreview').classList.contains('hidden'));
      const preview=new Image(); preview.src=photoData; await preview.decode();
      assert('photo resized to 960 pixels', preview.naturalWidth === 960);
      $('removePhoto').click();
      assert('remove photo clears draft', !photoData && $('photoPreview').classList.contains('hidden'));
      const invalid = new DataTransfer(); invalid.items.add(new File(['bad'], 'bad.heic', {type:'image/heic'})); $('mealPhoto').files=invalid.files;
      await $('mealPhoto').onchange();
      assert('unsupported photo rejected', !photoData && $('photoStatus').textContent.includes('JPG'));
      const broken = new DataTransfer(); broken.items.add(new File(['bad'], 'bad.png', {type:'image/png'})); $('mealPhoto').files=broken.files;
      await $('mealPhoto').onchange();
      assert('corrupt photo rejected', !photoData && $('photoStatus').textContent.includes('Couldn’t read'));
      const finalTransfer=new DataTransfer(); finalTransfer.items.add(file);
      $('mealPhoto').files=finalTransfer.files; await $('mealPhoto').onchange();
      assert('replacement photo ready', photoData.startsWith('data:image/jpeg;base64,'));
      $('mealAuthor').value='Group Tester'; $('mealName').value='<b>Photo test bowl</b>'; $('mealDescription').value='Rice and vegetables';
      $('mealServing').value='1 bowl'; $('mealCalories').value='450'; $('mealProtein').value='0'; $('mealCarbs').value=''; $('mealFat').value='12.5';
      $('mealCalories').value='-1'; assert('negative macros blocked', !$('mealCalories').checkValidity()); $('mealCalories').value='450';
      await $('shareMealForm').onsubmit({preventDefault(){},target:$('shareMealForm')});
      const post=meals.find(m => m.title === '<b>Photo test bowl</b>');
      await toggleCompliment(post.id);
      if (mode === 'personal') assert('compliment saved locally', JSON.parse(localStorage.getItem('platePalCompliments')).includes(post.id));
      assert('photo-only post with no recipe succeeds', post && post.ingredients.length === 0 && post.instructions.length === 0);
      assert('zero and unknown macros preserved', post.macros.protein === 0 && post.macros.carbs === null);
      assert('post title is escaped', document.querySelector('.meal-card h3').textContent === '<b>Photo test bowl</b>' && !document.querySelector('.meal-card h3 b'));
      assert('nutrition on feed card', document.querySelector('.nutrition').textContent.includes('450') && !document.querySelector('.nutrition').textContent.includes('g carbs'));
      if (mode === 'personal') assert('photo and macros stored locally', JSON.parse(localStorage.getItem('platePalMeals'))[0].image === post.image);
      else assert('photo and macros stored on server', (await groupRequest('/api/meals')).meals.some(m => m.id === post.id && m.image === post.image));
      openRecipe(post.id);
      assert('empty ingredients disable grocery action', $('groceryBtn').disabled);
      $('recipeModal').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
      assert('Escape closes recipe dialog', $('recipeModal').classList.contains('hidden'));
      toggleSave(post.id); document.querySelector('[data-filter="saved"]').click();
      assert('new post can be saved', document.querySelectorAll('.meal-card').length === 1);
      $('searchMeals').value='no such meal'; renderMeals(); assert('search empty state works', !!document.querySelector('.empty-state'));
      if (mode === 'personal') {
        $('mealName').value='Keep my draft'; $('mealDescription').value='Draft description';
        const original=Storage.prototype.setItem;
        Storage.prototype.setItem=function() { throw new DOMException('Quota exceeded', 'QuotaExceededError'); };
        await $('shareMealForm').onsubmit({preventDefault(){},target:$('shareMealForm')});
        Storage.prototype.setItem=original;
        assert('storage failure keeps draft and shows error', $('mealName').value==='Keep my draft' && !$('postError').classList.contains('hidden') && !meals.some(m => m.title==='Keep my draft'));
      }
    }
  } catch(error) { checks.push('FAIL ' + error.message + '\n' + error.stack); }
  window.plateTestResult = checks.join('\n');
  document.body.innerHTML = '<pre id="checks"></pre>';
  document.getElementById('checks').textContent = checks.join('\n');
})();
